"""
test_coverage_overlay.py — Unit Tests for the Coverage Overlay Engine
======================================================================

TESTING STRATEGY
----------------
The coverage overlay engine has one tricky dependency: it reads a binary
`.coverage` file created by coverage.py. We cannot create this file
manually in tests without executing real code.

We handle this with two strategies:

  1. MOCK TESTS (majority)
     We mock the `CoverageFileReader.read()` method to return fake
     LineCoverageData objects we control completely. This lets us test
     the annotation logic (the complex part) without any file I/O.

  2. INTEGRATION TESTS
     We use a real .coverage file generated by running a tiny Python
     file through coverage.py programmatically inside the test itself.
     This validates the file reader against a real coverage artifact.

HOW TO RUN
----------
  cd backend
  pytest tests/test_coverage_overlay.py -v
"""

import textwrap
from pathlib import Path

import pytest

from engines.blast_radius import (
    FileSymbolTable,
    SymbolDefinition,
)
from engines.coverage_overlay import (
    CoverageFileReader,
    LineCoverageData,
    SymbolCoverageAnnotator,
    overlay_to_json,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def write_file(directory: Path, rel_path: str, content: str) -> Path:
    full = directory / rel_path
    full.parent.mkdir(parents=True, exist_ok=True)
    full.write_text(textwrap.dedent(content), encoding="utf-8")
    return full


def make_symbol_definition(
    name: str,
    module_path: str,
    file_path: str,
    line_start: int,
    line_end: int,
    sym_type: str = "function",
) -> SymbolDefinition:
    return SymbolDefinition(
        name=name,
        qualified_name=f"{module_path}.{name}",
        symbol_type=sym_type,
        file_path=file_path,
        line_start=line_start,
        line_end=line_end,
    )


def make_file_table(
    module_path: str,
    file_path: str,
    definitions: list[SymbolDefinition],
) -> FileSymbolTable:
    table = FileSymbolTable(file_path=file_path, module_path=module_path)
    table.definitions = definitions
    return table


def make_line_coverage(
    file_path: str,
    covered: list[int],
    missing: list[int],
) -> LineCoverageData:
    total = len(covered) + len(missing)
    pct = len(covered) / total * 100.0 if total > 0 else 0.0
    return LineCoverageData(
        file_path=file_path,
        covered_lines=covered,
        missing_lines=missing,
        total_lines=total,
        coverage_percent=round(pct, 2),
    )


# ---------------------------------------------------------------------------
# TestSymbolCoverageAnnotator — the core annotation logic
# ---------------------------------------------------------------------------

class TestSymbolCoverageAnnotator:
    """
    Tests for the annotation logic that maps line coverage → symbol coverage.
    These tests use fabricated data only — no real .coverage file needed.
    """

    def test_fully_covered_symbol(self, tmp_path):
        """
        If all lines in the symbol's range appear in covered_lines,
        status should be "covered" and coverage_percent should be 100.
        """
        file_path = str(tmp_path / "auth" / "utils.py")
        defn = make_symbol_definition("validate_token", "auth.utils", file_path, 1, 5)
        table = make_file_table("auth.utils", file_path, [defn])

        # Lines 1, 2, 3, 4, 5 all covered
        cov = make_line_coverage(file_path, covered=[1, 2, 3, 4, 5], missing=[])

        annotator = SymbolCoverageAnnotator()
        result = annotator.annotate(
            symbol_tables={"auth.utils": table},
            coverage_data={file_path: cov},
            repo_root=tmp_path,
        )

        ann = result.annotations[0]
        assert ann.coverage_status == "covered"
        assert ann.coverage_percent == 100.0

    def test_completely_uncovered_symbol(self, tmp_path):
        """
        If no lines in the symbol's range were executed,
        status should be "uncovered".
        """
        file_path = str(tmp_path / "auth" / "utils.py")
        defn = make_symbol_definition("dead_code", "auth.utils", file_path, 10, 15)
        table = make_file_table("auth.utils", file_path, [defn])

        cov = make_line_coverage(file_path, covered=[1, 2, 3], missing=[10, 11, 12, 13, 14, 15])

        annotator = SymbolCoverageAnnotator()
        result = annotator.annotate({"auth.utils": table}, {file_path: cov}, tmp_path)

        ann = result.annotations[0]
        assert ann.coverage_status == "uncovered"
        assert ann.coverage_percent == 0.0

    def test_partially_covered_symbol(self, tmp_path):
        """
        If some but not all lines were executed, status should be "partial".
        """
        file_path = str(tmp_path / "utils.py")
        defn = make_symbol_definition("mixed", "utils", file_path, 1, 4)
        table = make_file_table("utils", file_path, [defn])

        # Lines 1, 2 covered; 3, 4 not covered
        cov = make_line_coverage(file_path, covered=[1, 2], missing=[3, 4])

        annotator = SymbolCoverageAnnotator()
        result = annotator.annotate({"utils": table}, {file_path: cov}, tmp_path)

        ann = result.annotations[0]
        assert ann.coverage_status == "partial"
        assert 0 < ann.coverage_percent < 100

    def test_unknown_status_when_no_coverage_file(self, tmp_path):
        """
        If we have no coverage data for a file at all (it was never
        measured), status should be "unknown" — not "uncovered".

        This distinction matters: "uncovered" means tested but not
        executed. "unknown" means we simply have no data.
        """
        file_path = str(tmp_path / "utils.py")
        defn = make_symbol_definition("helper", "utils", file_path, 1, 3)
        table = make_file_table("utils", file_path, [defn])

        annotator = SymbolCoverageAnnotator()
        # Pass empty coverage_data — no data for this file
        result = annotator.annotate({"utils": table}, {}, tmp_path)

        ann = result.annotations[0]
        assert ann.coverage_status == "unknown"

    def test_uncovered_module_paths_populated(self, tmp_path):
        """
        The result's uncovered_module_paths list must contain the module
        path of any file that has at least one uncovered symbol.

        This list is what the BlastRadius engine uses for risk scoring.
        """
        file_path = str(tmp_path / "auth" / "utils.py")
        (tmp_path / "auth").mkdir(parents=True, exist_ok=True)
        Path(file_path).write_text("def foo(): pass\n")

        defn = make_symbol_definition("foo", "auth.utils", file_path, 1, 1)
        table = make_file_table("auth.utils", file_path, [defn])

        cov = make_line_coverage(file_path, covered=[], missing=[1])

        annotator = SymbolCoverageAnnotator()
        result = annotator.annotate({"auth.utils": table}, {file_path: cov}, tmp_path)

        assert "auth.utils" in result.uncovered_module_paths

    def test_overall_coverage_percent_calculated(self, tmp_path):
        """
        overall_coverage_percent should be the aggregate coverage across
        all measured files.
        """
        fp1 = str(tmp_path / "a.py")
        fp2 = str(tmp_path / "b.py")

        defn1 = make_symbol_definition("f1", "a", fp1, 1, 2)
        defn2 = make_symbol_definition("f2", "b", fp2, 1, 2)
        tables = {
            "a": make_file_table("a", fp1, [defn1]),
            "b": make_file_table("b", fp2, [defn2]),
        }

        # a: 2/2 covered, b: 1/2 covered → total 3/4 = 75%
        cov_data = {
            fp1: make_line_coverage(fp1, covered=[1, 2], missing=[]),
            fp2: make_line_coverage(fp2, covered=[1], missing=[2]),
        }

        annotator = SymbolCoverageAnnotator()
        result = annotator.annotate(tables, cov_data, tmp_path)

        assert result.overall_coverage_percent == pytest.approx(75.0, abs=1.0)

    def test_files_with_no_coverage_data_tracked(self, tmp_path):
        """
        The result should record which files had no coverage data at all.
        """
        file_path = str(tmp_path / "orphan.py")
        defn = make_symbol_definition("orphan_func", "orphan", file_path, 1, 3)
        table = make_file_table("orphan", file_path, [defn])

        annotator = SymbolCoverageAnnotator()
        result = annotator.annotate({"orphan": table}, {}, tmp_path)

        assert "orphan" in result.files_with_no_coverage_data

    def test_multiple_symbols_annotated(self, tmp_path):
        """
        A file with multiple function definitions should produce one
        annotation per definition.
        """
        file_path = str(tmp_path / "utils.py")
        definitions = [
            make_symbol_definition("func_a", "utils", file_path, 1, 3),
            make_symbol_definition("func_b", "utils", file_path, 5, 8),
            make_symbol_definition("func_c", "utils", file_path, 10, 12),
        ]
        table = make_file_table("utils", file_path, definitions)

        cov = make_line_coverage(
            file_path,
            covered=[1, 2, 3, 5, 6],
            missing=[7, 8, 10, 11, 12],
        )

        annotator = SymbolCoverageAnnotator()
        result = annotator.annotate({"utils": table}, {file_path: cov}, tmp_path)

        assert len(result.annotations) == 3
        statuses = {a.qualified_name: a.coverage_status for a in result.annotations}
        assert statuses["utils.func_a"] == "covered"
        assert statuses["utils.func_b"] == "partial"
        assert statuses["utils.func_c"] == "uncovered"


# ---------------------------------------------------------------------------
# TestCoverageFileReader — tests the .coverage file reader
# ---------------------------------------------------------------------------

class TestCoverageFileReader:
    """
    Tests for reading actual .coverage files.
    We generate a real .coverage file by running coverage.py
    programmatically on a tiny Python script.
    """

    def _generate_coverage_file(self, tmp_path: Path) -> tuple[Path, Path]:
        """
        Create a tiny Python file, run it under coverage.py, and return
        the paths to (source_file, coverage_file).
        """
        try:
            import coverage as coverage_lib
        except ImportError:
            pytest.skip("coverage package not installed")

        source = tmp_path / "subject.py"
        source.write_text(textwrap.dedent("""\
            def covered():
                x = 1
                return x

            def uncovered():
                y = 2
                return y
        """))

        cov_file = tmp_path / ".coverage"
        cov = coverage_lib.Coverage(data_file=str(cov_file))
        cov.start()
        try:
            # Execute only `covered()`, leaving `uncovered()` untouched
            ns = {}
            exec(compile(source.read_text(), str(source), "exec"), ns)
            ns["covered"]()
        finally:
            cov.stop()
            cov.save()

        return source, cov_file

    def test_reader_returns_line_coverage_data(self, tmp_path):
        """
        The reader should return a dict containing LineCoverageData
        for the measured file.
        """
        source, cov_file = self._generate_coverage_file(tmp_path)

        reader = CoverageFileReader()
        data = reader.read(cov_file)

        # At least one file should be in the data
        assert len(data) > 0

    def test_covered_lines_are_recorded(self, tmp_path):
        """
        Lines executed during the test run must appear in covered_lines.
        """
        source, cov_file = self._generate_coverage_file(tmp_path)

        reader = CoverageFileReader()
        data = reader.read(cov_file)

        # Find our source file in the data (path matching)
        match = next(
            (v for k, v in data.items() if "subject" in k),
            None,
        )
        assert match is not None, "subject.py not found in coverage data"
        assert len(match.covered_lines) > 0

    def test_raises_on_missing_coverage_file(self, tmp_path):
        """
        Attempting to read a non-existent .coverage file must raise
        FileNotFoundError — not return an empty dict silently.
        """
        reader = CoverageFileReader()
        with pytest.raises(FileNotFoundError):
            reader.read(tmp_path / "nonexistent_coverage_file")


# ---------------------------------------------------------------------------
# TestBuildCoverageOverlay — Integration Test (full pipeline)
# ---------------------------------------------------------------------------

class TestBuildCoverageOverlay:
    """
    End-to-end test of build_coverage_overlay() — the public API function.
    """

    def test_full_pipeline_json_serialisable(self, tmp_path):
        """
        The result must be serialisable to JSON. The API layer depends on this.
        """
        import json

        file_path = str(tmp_path / "utils.py")
        (tmp_path / "utils.py").write_text("def foo(): pass\n")

        defn = make_symbol_definition("foo", "utils", file_path, 1, 1)
        table = make_file_table("utils", file_path, [defn])

        annotator = SymbolCoverageAnnotator()
        result = annotator.annotate({"utils": table}, {}, tmp_path)

        json_str = overlay_to_json(result)
        parsed = json.loads(json_str)

        assert "annotations" in parsed
        assert "overall_coverage_percent" in parsed
        assert "uncovered_module_paths" in parsed